spring:
  application:
    name: gulimall-third-party
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    alicloud:
      access-key: LTAI5t9TjA8xcrfu5din929m
      secret-key: bQRQYDLAgdS1PSGb7oc6VaM5OXZ0g4
      oss:
        endpoint: oss-cn-beijing.aliyuncs.com
        bucket: lzkguli-file
server:
  port: 30000